import React from 'react';
import { Box, Typography, Button, Alert } from '@mui/material';
import { ArrowBack } from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';
import InterviewerLayout from '../../components/InterviewerLayout';

/**
 * This page previously showed pre-generated questions per candidate/round.
 * Questions are now generated on-demand when you start an interview session,
 * so there is no separate preview step.
 */
function InterviewerQuestionsPage() {
  const navigate = useNavigate();

  return (
    <InterviewerLayout>
      <Button
        startIcon={<ArrowBack />}
        size="small"
        onClick={() => navigate('/interviewer/assignments')}
        sx={{ mb: 2 }}
      >
        Back to Assignments
      </Button>

      <Box sx={{ mt: 6, textAlign: 'center' }}>
        <Alert severity="info" sx={{ mb: 3, maxWidth: 480, mx: 'auto', textAlign: 'left' }}>
          Questions are now generated by AI when you start the interview session. There is no separate preview step.
        </Alert>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
          Go to your assignments, select a candidate, and click <b>Start Interview</b> to generate questions and begin the session.
        </Typography>
        <Button variant="contained" onClick={() => navigate('/interviewer/assignments')}>
          Go to Assignments
        </Button>
      </Box>
    </InterviewerLayout>
  );
}

export default InterviewerQuestionsPage;
