package com.p99softtraining.hiresense.dto;

import com.p99softtraining.hiresense.enums.DifficultyLevel;

/**
 * DTO representing a single interview question generated by the AI question generator.
 *
 * @param questionText    The text of the interview question (must be non-blank).
 * @param skill           The skill this question targets (from primarySkills or secondarySkills).
 * @param difficultyLevel The difficulty of the question (EASY, MEDIUM, or HARD).
 */
public record GeneratedQuestion(
        String questionText,
        String skill,
        DifficultyLevel difficultyLevel
) {}
